pdf_path: "../pdf/styl.pdf"
vector_db_path: "../vector_db_faiss"

embedding_model_name: "sdadas/mmlw-roberta-large"
llm_model_name: "mwiewior/bielik"

template: |
  Use the following information to answer the question at the end.
  If you don't know the answer, just say that you don't know, and don't try to make up an answer.
  Use a maximum of three sentences and try to make your answer as brief as possible.
  Always add "thank you for the question!" at the end of your answer.
  {context}
  Question: {question}
  Helpful answer, it should be in English: